### PR TITLE
Add: Homepage and Authentication

### PR DESCRIPTION
**Pull request by samflab**
I have included:
- Home Page:
1. Hero Content with an image on the side
2. Genres / Category section made with grids
3. Trending products section, again with grids

- On the Navbar you can find the authentication tabs when clicked on the account/user icon:
 1. Signup Drawer
 2. Login Drawer
 3. Reset Password Drawer
 
**Screenshots**
image

**Screen Recorder**

https://user-images.githubusercontent.com/55777560/152472428-954a51ab-6c72-4951-95ed-2581e7c11dc7.mp4

### CODE REVIEW

**Review by Anish-JS — APPROVED** [review]
looks good

**Review by aniketxparihar — APPROVED** [review]
Looks Good

**Review by NtshVrm — APPROVED** [review]

**Review by Ash-D23 — APPROVED** [review]
screens looks amazing

**Review by mohammadkhizerkhan — APPROVED** [review]
Looks nice

**Pull request merged**
